include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    unnecessary_underscores: ignore
    one_member_abstracts: ignore ignore
    invalid_annotation_target: ignore
  exclude:
    - lib/l10n/gen/*
linter:
  rules:
    public_member_api_docs: false
