name: planets_app_test
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  go_router: ^16.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path: ^1.9.1
  path_provider: ^2.1.5
  responsive_builder: ^0.7.1
  riverpod: ^2.6.1
  slang: ^4.8.1
  slang_build_runner: ^4.8.0
  slang_flutter: ^4.8.0
  very_good_analysis: ^10.0.0

flutter_gen:
  output: lib/src/gen/
  integrations:
    flutter_svg: true

  assets:
    outputs:
      package_parameter_enabled: false

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.0
  mocktail: ^1.0.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/png/
    - assets/gif/
